; move ids
; indexes for:
; - Moves (see data/moves/moves.asm)
; - MoveNames (see data/moves/names.asm)
; - MoveDescriptions (see data/moves/descriptions.asm)
; - BattleAnimations (see data/moves/animations.asm)
	const_def
	const NO_MOVE      ; 00
	const POUND        ; 01
	const KARATE_CHOP  ; 02
	const DOUBLESLAP   ; 03
	const COMET_PUNCH  ; 04
	const MEGA_PUNCH   ; 05
	const PAY_DAY      ; 06
	const FIRE_PUNCH   ; 07
	const ICE_PUNCH    ; 08
	const THUNDERPUNCH ; 09
	const SCRATCH      ; 0a
	const VICEGRIP     ; 0b
	const GUILLOTINE   ; 0c
	const SWORDS_DANCE ; 0d
	const CUT          ; 0e
	const GUST         ; 0f
	const WING_ATTACK  ; 10
	const FLY          ; 11
	const SLAM         ; 12
	const VINE_WHIP    ; 13
	const STOMP        ; 14
	const DOUBLE_KICK  ; 15
	const MEGA_KICK    ; 16
	const JUMP_KICK    ; 17
	const ROLLING_KICK ; 18
	const SAND_ATTACK  ; 19
	const HEADBUTT     ; 1a
	const HORN_ATTACK  ; 1b
	const FURY_ATTACK  ; 1c
	const HORN_DRILL   ; 1d
	const TACKLE       ; 1e
	const BODY_SLAM    ; 1f
	const WRAP         ; 20
	const TAKE_DOWN    ; 21
	const THRASH       ; 22
	const DOUBLE_EDGE  ; 23
	const TAIL_WHIP    ; 24
	const POISON_STING ; 25
	const TWINEEDLE    ; 26
	const PIN_MISSILE  ; 27
	const LEER         ; 28
	const BITE         ; 29
	const GROWL        ; 2a
	const ROAR         ; 2b
	const SING         ; 2c
	const SUPERSONIC   ; 2d
	const SONICBOOM    ; 2e
	const DISABLE      ; 2f
	const ACID         ; 30
	const EMBER        ; 31
	const FLAMETHROWER ; 32
	const MIST         ; 33
	const WATER_GUN    ; 34
	const HYDRO_PUMP   ; 35
	const SURF         ; 36
	const ICE_BEAM     ; 37
	const BLIZZARD     ; 38
	const PSYBEAM      ; 39
	const BUBBLEBEAM   ; 3a
	const AURORA_BEAM  ; 3b
	const HYPER_BEAM   ; 3c
	const PECK         ; 3d
	const DRILL_PECK   ; 3e
	const SUBMISSION   ; 3f
	const LOW_KICK     ; 40
	const COUNTER      ; 41
	const SEISMIC_TOSS ; 42
	const STRENGTH     ; 43
	const ABSORB       ; 44
	const MEGA_DRAIN   ; 45
	const LEECH_SEED   ; 46
	const GROWTH       ; 47
	const RAZOR_LEAF   ; 48
	const SOLARBEAM    ; 49
	const POISONPOWDER ; 4a
	const STUN_SPORE   ; 4b
	const SLEEP_POWDER ; 4c
	const PETAL_DANCE  ; 4d
	const STRING_SHOT  ; 4e
	const DRAGON_RAGE  ; 4f
	const FIRE_SPIN    ; 50
	const THUNDERSHOCK ; 51
	const THUNDERBOLT  ; 52
	const THUNDER_WAVE ; 53
	const THUNDER      ; 54
	const ROCK_THROW   ; 55
	const EARTHQUAKE   ; 56
	const FISSURE      ; 57
	const DIG          ; 58
	const TOXIC        ; 59
	const CONFUSION    ; 5a
	const PSYCHIC_M    ; 5b
	const HYPNOSIS     ; 5c
	const MEDITATE     ; 5d
	const AGILITY      ; 5e
	const QUICK_ATTACK ; 5f
	const RAGE         ; 60
	const TELEPORT     ; 61
	const NIGHT_SHADE  ; 62
	const MIMIC        ; 63
	const SCREECH      ; 64
	const DOUBLE_TEAM  ; 65
	const RECOVER      ; 66
	const HARDEN       ; 67
	const MINIMIZE     ; 68
	const SMOKESCREEN  ; 69
	const CONFUSE_RAY  ; 6a
	const WITHDRAW     ; 6b
	const DEFENSE_CURL ; 6c
	const BARRIER      ; 6d
	const LIGHT_SCREEN ; 6e
	const HAZE         ; 6f
	const REFLECT      ; 70
	const FOCUS_ENERGY ; 71
	const BIDE         ; 72
	const METRONOME    ; 73
	const MIRROR_MOVE  ; 74
	const SELFDESTRUCT ; 75
	const EGG_BOMB     ; 76
	const LICK         ; 77
	const SMOG         ; 78
	const SLUDGE       ; 79
	const BONE_CLUB    ; 7a
	const FIRE_BLAST   ; 7b
	const WATERFALL    ; 7c
	const CLAMP        ; 7d
	const SWIFT        ; 7e
	const SKULL_BASH   ; 7f
	const SPIKE_CANNON ; 80
	const CONSTRICT    ; 81
	const AMNESIA      ; 82
	const KINESIS      ; 83
	const SOFTBOILED   ; 84
	const HI_JUMP_KICK ; 85
	const GLARE        ; 86
	const DREAM_EATER  ; 87
	const POISON_GAS   ; 88
	const BARRAGE      ; 89
	const LEECH_LIFE   ; 8a
	const LOVELY_KISS  ; 8b
	const SKY_ATTACK   ; 8c
	const TRANSFORM    ; 8d
	const BUBBLE       ; 8e
	const DIZZY_PUNCH  ; 8f
	const SPORE        ; 90
	const FLASH        ; 91
	const PSYWAVE      ; 92
	const SPLASH       ; 93
	const ACID_ARMOR   ; 94
	const CRABHAMMER   ; 95
	const EXPLOSION    ; 96
	const FURY_SWIPES  ; 97
	const BONEMERANG   ; 98
	const REST         ; 99
	const ROCK_SLIDE   ; 9a
	const HYPER_FANG   ; 9b
	const SHARPEN      ; 9c
	const CONVERSION   ; 9d
	const TRI_ATTACK   ; 9e
	const SUPER_FANG   ; 9f
	const SLASH        ; a0
	const SUBSTITUTE   ; a1
	const SKETCH       ; a2
	const TRIPLE_KICK  ; a3
	const THIEF        ; a4
	const SPIDER_WEB   ; a5
	const MIND_READER  ; a6
	const NIGHTMARE    ; a7
	const FLAME_WHEEL  ; a8
	const SNORE        ; a9
	const CURSE        ; aa
	const FLAIL        ; ab
	const CONVERSION2  ; ac
	const AEROBLAST    ; ad
	const COTTON_SPORE ; ae
	const REVERSAL     ; af
	const SPITE        ; b0
	const POWDER_SNOW  ; b1
	const PROTECT      ; b2
	const MACH_PUNCH   ; b3
	const SCARY_FACE   ; b4
	const FAINT_ATTACK ; b5
	const SWEET_KISS   ; b6
	const BELLY_DRUM   ; b7
	const SLUDGE_BOMB  ; b8
	const MUD_SLAP     ; b9
	const OCTAZOOKA    ; ba
	const SPIKES       ; bb
	const ZAP_CANNON   ; bc
	const FORESIGHT    ; bd
	const DESTINY_BOND ; be
	const PERISH_SONG  ; bf
	const ICY_WIND     ; c0
	const DETECT       ; c1
	const BONE_RUSH    ; c2
	const LOCK_ON      ; c3
	const OUTRAGE      ; c4
	const SANDSTORM    ; c5
	const GIGA_DRAIN   ; c6
	const ENDURE       ; c7
	const CHARM        ; c8
	const ROLLOUT      ; c9
	const FALSE_SWIPE  ; ca
	const SWAGGER      ; cb
	const MILK_DRINK   ; cc
	const SPARK        ; cd
	const FURY_CUTTER  ; ce
	const STEEL_WING   ; cf
	const MEAN_LOOK    ; d0
	const ATTRACT      ; d1
	const SLEEP_TALK   ; d2
	const HEAL_BELL    ; d3
	const RETURN       ; d4
	const PRESENT      ; d5
	const FRUSTRATION  ; d6
	const SAFEGUARD    ; d7
	const PAIN_SPLIT   ; d8
	const SACRED_FIRE  ; d9
	const MAGNITUDE    ; da
	const DYNAMICPUNCH ; db
	const MEGAHORN     ; dc
	const DRAGONBREATH ; dd
	const BATON_PASS   ; de
	const ENCORE       ; df
	const PURSUIT      ; e0
	const RAPID_SPIN   ; e1
	const SWEET_SCENT  ; e2
	const IRON_TAIL    ; e3
	const METAL_CLAW   ; e4
	const VITAL_THROW  ; e5
	const MORNING_SUN  ; e6
	const SYNTHESIS    ; e7
	const MOONLIGHT    ; e8
	const HIDDEN_POWER ; e9
	const CROSS_CHOP   ; ea
	const TWISTER      ; eb
	const RAIN_DANCE   ; ec
	const SUNNY_DAY    ; ed
	const CRUNCH       ; ee
	const MIRROR_COAT  ; ef
	const PSYCH_UP     ; f0
	const EXTREMESPEED ; f1
	const ANCIENTPOWER ; f2
	const SHADOW_BALL  ; f3
	const FUTURE_SIGHT ; f4
	const ROCK_SMASH   ; f5
	const WHIRLPOOL    ; f6
	const BEAT_UP      ; f7
	const HAIL         ; f8
	const LEAF_BLADE   ; f9
	const DARK_PULSE   ; fa
	const SNARL        ; fb
	const CHARM_VOICE  ; fc
	const MOONBLAST    ; fd
	const LEAFAGE      ; fe
	const STRUGGLE     ; ff
DEF NUM_ATTACKS EQU const_value - 1

; Battle animations use the same constants as the moves up to this point
	const_next $100
	const ANIM_SWEET_SCENT_2     ; 100
	const ANIM_THROW_POKE_BALL   ; 101
	const ANIM_SEND_OUT_MON      ; 102
	const ANIM_RETURN_MON        ; 103
	const ANIM_CONFUSED          ; 104
	const ANIM_SLP               ; 105
	const ANIM_BRN               ; 106
	const ANIM_PSN               ; 107
	const ANIM_SAP               ; 108
	const ANIM_FRZ               ; 109
	const ANIM_PAR               ; 10a
	const ANIM_IN_LOVE           ; 10b
	const ANIM_IN_SANDSTORM      ; 10c
	const ANIM_IN_NIGHTMARE      ; 10d
	const ANIM_IN_WHIRLPOOL      ; 10e
; battle anims
	const ANIM_MISS              ; 10f
	const ANIM_ENEMY_DAMAGE      ; 110
	const ANIM_ENEMY_STAT_DOWN   ; 111
	const ANIM_PLAYER_STAT_DOWN  ; 112
	const ANIM_PLAYER_DAMAGE     ; 113
	const ANIM_WOBBLE            ; 114
	const ANIM_SHAKE             ; 115
	const ANIM_HIT_CONFUSION     ; 116
	const ANIM_IN_HAIL           ; 117
DEF NUM_BATTLE_ANIMS EQU const_value - 1

; wNumHits uses offsets from ANIM_MISS
	const_def
	const BATTLEANIM_NONE
	const BATTLEANIM_ENEMY_DAMAGE
	const BATTLEANIM_ENEMY_STAT_DOWN
	const BATTLEANIM_PLAYER_STAT_DOWN
	const BATTLEANIM_PLAYER_DAMAGE
	const BATTLEANIM_WOBBLE
	const BATTLEANIM_SHAKE
	const BATTLEANIM_HIT_CONFUSION
