; move ids
; indexes for:
; - Moves (see data/moves/moves.asm)
; - MoveNames (see data/moves/names.asm)
; - MoveDescriptions (see data/moves/descriptions.asm)
; - BattleAnimations (see data/moves/animations.asm)
	const_def
	const NO_MOVE      ; 00
	const POUND        ; 01
	const KARATE_CHOP  ; 02
	const DOUBLESLAP   ; 03
	const COMET_PUNCH  ; 04
	const MEGA_PUNCH   ; 05
	const PAY_DAY      ; 06
	const FIRE_PUNCH   ; 07
	const ICE_PUNCH    ; 08
	const THUNDERPUNCH ; 09
	const SCRATCH      ; 0a
	const VICEGRIP     ; 0b
	const GUILLOTINE   ; 0c
	const RAZOR_WIND   ; 0d
	const SWORDS_DANCE ; 0e
	const CUT          ; 0f
	const GUST         ; 10
	const WING_ATTACK  ; 11
	const FLY          ; 12
	const BIND         ; 13
	const SLAM         ; 14
	const VINE_WHIP    ; 15
	const STOMP        ; 16
	const DOUBLE_KICK  ; 17
	const MEGA_KICK    ; 18
	const JUMP_KICK    ; 19
	const ROLLING_KICK ; 1a
	const SAND_ATTACK  ; 1b
	const HEADBUTT     ; 1c
	const HORN_ATTACK  ; 1d
	const FURY_ATTACK  ; 1e
	const HORN_DRILL   ; 1f
	const TACKLE       ; 20
	const BODY_SLAM    ; 21
	const WRAP         ; 22
	const TAKE_DOWN    ; 23
	const THRASH       ; 24
	const DOUBLE_EDGE  ; 25
	const TAIL_WHIP    ; 26
	const POISON_STING ; 27
	const TWINEEDLE    ; 28
	const PIN_MISSILE  ; 29
	const LEER         ; 2a
	const BITE         ; 2b
	const GROWL        ; 2c
	const ROAR         ; 2d
	const SING         ; 2e
	const SUPERSONIC   ; 2f
	const SONICBOOM    ; 30
	const DISABLE      ; 31
	const ACID         ; 32
	const EMBER        ; 33
	const FLAMETHROWER ; 34
	const MIST         ; 35
	const WATER_GUN    ; 36
	const HYDRO_PUMP   ; 37
	const SURF         ; 38
	const ICE_BEAM     ; 39
	const BLIZZARD     ; 3a
	const PSYBEAM      ; 3b
	const BUBBLEBEAM   ; 3c
	const AURORA_BEAM  ; 3d
	const HYPER_BEAM   ; 3e
	const PECK         ; 3f
	const DRILL_PECK   ; 40
	const SUBMISSION   ; 41
	const LOW_KICK     ; 42
	const COUNTER      ; 43
	const SEISMIC_TOSS ; 44
	const STRENGTH     ; 45
	const ABSORB       ; 46
	const MEGA_DRAIN   ; 47
	const LEECH_SEED   ; 48
	const GROWTH       ; 49
	const RAZOR_LEAF   ; 4a
	const SOLARBEAM    ; 4b
	const POISONPOWDER ; 4c
	const STUN_SPORE   ; 4d
	const SLEEP_POWDER ; 4e
	const PETAL_DANCE  ; 4f
	const STRING_SHOT  ; 50
	const DRAGON_RAGE  ; 51
	const FIRE_SPIN    ; 52
	const THUNDERSHOCK ; 53
	const THUNDERBOLT  ; 54
	const THUNDER_WAVE ; 55
	const THUNDER      ; 56
	const ROCK_THROW   ; 57
	const EARTHQUAKE   ; 58
	const FISSURE      ; 59
	const DIG          ; 5a
	const TOXIC        ; 5b
	const CONFUSION    ; 5c
	const PSYCHIC_M    ; 5d
	const HYPNOSIS     ; 5e
	const MEDITATE     ; 5f
	const AGILITY      ; 60
	const QUICK_ATTACK ; 61
	const RAGE         ; 62
	const TELEPORT     ; 63
	const NIGHT_SHADE  ; 64
	const MIMIC        ; 65
	const SCREECH      ; 66
	const DOUBLE_TEAM  ; 67
	const RECOVER      ; 68
	const HARDEN       ; 69
	const MINIMIZE     ; 6a
	const SMOKESCREEN  ; 6b
	const CONFUSE_RAY  ; 6c
	const WITHDRAW     ; 6d
	const DEFENSE_CURL ; 6e
	const BARRIER      ; 6f
	const LIGHT_SCREEN ; 70
	const HAZE         ; 71
	const REFLECT      ; 72
	const FOCUS_ENERGY ; 73
	const BIDE         ; 74
	const METRONOME    ; 75
	const MIRROR_MOVE  ; 76
	const SELFDESTRUCT ; 77
	const EGG_BOMB     ; 78
	const LICK         ; 79
	const SMOG         ; 7a
	const SLUDGE       ; 7b
	const BONE_CLUB    ; 7c
	const FIRE_BLAST   ; 7d
	const WATERFALL    ; 7e
	const CLAMP        ; 7f
	const SWIFT        ; 80
	const SKULL_BASH   ; 81
	const SPIKE_CANNON ; 82
	const CONSTRICT    ; 83
	const AMNESIA      ; 84
	const KINESIS      ; 85
	const SOFTBOILED   ; 86
	const HI_JUMP_KICK ; 87
	const GLARE        ; 88
	const DREAM_EATER  ; 89
	const POISON_GAS   ; 8a
	const BARRAGE      ; 8b
	const LEECH_LIFE   ; 8c
	const LOVELY_KISS  ; 8d
	const SKY_ATTACK   ; 8e
	const TRANSFORM    ; 8f
	const BUBBLE       ; 90
	const DIZZY_PUNCH  ; 91
	const SPORE        ; 92
	const FLASH        ; 93
	const PSYWAVE      ; 94
	const SPLASH       ; 95
	const ACID_ARMOR   ; 96
	const CRABHAMMER   ; 97
	const EXPLOSION    ; 98
	const FURY_SWIPES  ; 99
	const BONEMERANG   ; 9a
	const REST         ; 9b
	const ROCK_SLIDE   ; 9c
	const HYPER_FANG   ; 9d
	const SHARPEN      ; 9e
	const CONVERSION   ; 9f
	const TRI_ATTACK   ; a0
	const SUPER_FANG   ; a1
	const SLASH        ; a2
	const SUBSTITUTE   ; a3
	const SKETCH       ; a4
	const TRIPLE_KICK  ; a5
	const THIEF        ; a6
	const SPIDER_WEB   ; a7
	const MIND_READER  ; a8
	const NIGHTMARE    ; a9
	const FLAME_WHEEL  ; aa
	const SNORE        ; ab
	const CURSE        ; ac
	const FLAIL        ; ad
	const CONVERSION2  ; ae
	const AEROBLAST    ; af
	const COTTON_SPORE ; b0
	const REVERSAL     ; b1
	const SPITE        ; b2
	const POWDER_SNOW  ; b3
	const PROTECT      ; b4
	const MACH_PUNCH   ; b5
	const SCARY_FACE   ; b6
	const FAINT_ATTACK ; b7
	const SWEET_KISS   ; b8
	const BELLY_DRUM   ; b9
	const SLUDGE_BOMB  ; ba
	const MUD_SLAP     ; bb
	const OCTAZOOKA    ; bc
	const SPIKES       ; bd
	const ZAP_CANNON   ; be
	const FORESIGHT    ; bf
	const DESTINY_BOND ; c0
	const PERISH_SONG  ; c1
	const ICY_WIND     ; c2
	const DETECT       ; c3
	const BONE_RUSH    ; c4
	const LOCK_ON      ; c5
	const OUTRAGE      ; c6
	const SANDSTORM    ; c7
	const GIGA_DRAIN   ; c8
	const ENDURE       ; c9
	const CHARM        ; ca
	const ROLLOUT      ; cb
	const FALSE_SWIPE  ; cc
	const SWAGGER      ; cd
	const MILK_DRINK   ; ce
	const SPARK        ; cf
	const FURY_CUTTER  ; d0
	const STEEL_WING   ; d1
	const MEAN_LOOK    ; d2
	const ATTRACT      ; d3
	const SLEEP_TALK   ; d4
	const HEAL_BELL    ; d5
	const RETURN       ; d6
	const PRESENT      ; d7
	const FRUSTRATION  ; d8
	const SAFEGUARD    ; d9
	const PAIN_SPLIT   ; da
	const SACRED_FIRE  ; db
	const MAGNITUDE    ; dc
	const DYNAMICPUNCH ; dd
	const MEGAHORN     ; de
	const DRAGONBREATH ; df
	const BATON_PASS   ; e0
	const ENCORE       ; e1
	const PURSUIT      ; e2
	const RAPID_SPIN   ; e3
	const SWEET_SCENT  ; e4
	const IRON_TAIL    ; e5
	const METAL_CLAW   ; e6
	const VITAL_THROW  ; e7
	const MORNING_SUN  ; e8
	const SYNTHESIS    ; e9
	const MOONLIGHT    ; ea
	const HIDDEN_POWER ; eb
	const CROSS_CHOP   ; ec
	const TWISTER      ; ed
	const RAIN_DANCE   ; ee
	const SUNNY_DAY    ; ef
	const CRUNCH       ; f0
	const MIRROR_COAT  ; f1
	const PSYCH_UP     ; f2
	const EXTREMESPEED ; f3
	const ANCIENTPOWER ; f4
	const SHADOW_BALL  ; f5
	const FUTURE_SIGHT ; f6
	const ROCK_SMASH   ; f7
	const WHIRLPOOL    ; f8
	const BEAT_UP      ; f9
	const HAIL         ; fa
	const LEAF_BLADE   ; fb
	const SNARL        ; fc
	const CHARM_VOICE  ; fd
	const LEAFAGE      ; fe
	const STRUGGLE     ; ff
DEF NUM_ATTACKS EQU const_value - 1

; Battle animations use the same constants as the moves up to this point
	const_next $100
	const ANIM_SWEET_SCENT_2     ; 100
	const ANIM_THROW_POKE_BALL   ; 101
	const ANIM_SEND_OUT_MON      ; 102
	const ANIM_RETURN_MON        ; 103
	const ANIM_CONFUSED          ; 104
	const ANIM_SLP               ; 105
	const ANIM_BRN               ; 106
	const ANIM_PSN               ; 107
	const ANIM_SAP               ; 108
	const ANIM_FRZ               ; 109
	const ANIM_PAR               ; 10a
	const ANIM_IN_LOVE           ; 10b
	const ANIM_IN_SANDSTORM      ; 10c
	const ANIM_IN_NIGHTMARE      ; 10d
	const ANIM_IN_WHIRLPOOL      ; 10e
; battle anims
	const ANIM_MISS              ; 10f
	const ANIM_ENEMY_DAMAGE      ; 110
	const ANIM_ENEMY_STAT_DOWN   ; 111
	const ANIM_PLAYER_STAT_DOWN  ; 112
	const ANIM_PLAYER_DAMAGE     ; 113
	const ANIM_WOBBLE            ; 114
	const ANIM_SHAKE             ; 115
	const ANIM_HIT_CONFUSION     ; 116
	const ANIM_IN_HAIL           ; 117
DEF NUM_BATTLE_ANIMS EQU const_value - 1

; wNumHits uses offsets from ANIM_MISS
	const_def
	const BATTLEANIM_NONE
	const BATTLEANIM_ENEMY_DAMAGE
	const BATTLEANIM_ENEMY_STAT_DOWN
	const BATTLEANIM_PLAYER_STAT_DOWN
	const BATTLEANIM_PLAYER_DAMAGE
	const BATTLEANIM_WOBBLE
	const BATTLEANIM_SHAKE
	const BATTLEANIM_HIT_CONFUSION
