; pokemon ids
; indexes for:
; - PokemonNames (see data/pokemon/names.asm)
; - BaseData (see data/pokemon/base_stats.asm)
; - EvosAttacksPointers (see data/pokemon/evos_attacks_pointers.asm)
; - EggMovePointers (see data/pokemon/egg_move_pointers.asm)
; - PokemonCries (see data/pokemon/cries.asm)
; - MonMenuIcons (see data/pokemon/menu_icons.asm)
; - PokemonPicPointers (see data/pokemon/pic_pointers.asm)
; - PokemonPalettes (see data/pokemon/palettes.asm)
; - PokedexDataPointerTable (see data/pokemon/dex_entry_pointers.asm)
; - AnimationPointers (see gfx/pokemon/anim_pointers.asm)
; - AnimationIdlePointers (see gfx/pokemon/idle_pointers.asm)
; - BitmasksPointers (see gfx/pokemon/bitmask_pointers.asm)
; - FramesPointers (see gfx/pokemon/frame_pointers.asm)
	const_def 1
	const ROWLET     ; 01
	const DARTRIX    ; 02
	const DECIDUEYE  ; 03
	const CHIMCHAR   ; 04
	const MONFERNO   ; 05
	const INFERNAPE  ; 06
	const FROAKIE    ; 07
	const FROGADIER  ; 08
	const GRENINJA   ; 09
	const PICHU      ; 0a
	const PIKACHU    ; 0b
	const RAICHU     ; 0c
	const EEVEE      ; 0d
	const VAPOREON   ; 0e
	const JOLTEON    ; 0f
	const FLAREON    ; 10
	const ESPEON     ; 11
	const UMBREON    ; 12
	const LEAFEON    ; 13
	const GLACEON    ; 14
	const SYLVEON    ; 15
	const CATERPIE   ; 16
	const METAPOD    ; 17
	const BUTTERFREE ; 18
	const WEEDLE     ; 19
	const KAKUNA     ; 1a
	const BEEDRILL   ; 1b
	const RATTATA    ; 1c
	const RATICATE   ; 1d
	const SPEAROW    ; 1e
	const FEAROW     ; 1f
	const EKANS      ; 20
	const ARBOK      ; 21
	const SANDSHREW  ; 22
	const SANDSLASH  ; 23
	const NIDORAN_F  ; 24
	const NIDORINA   ; 25
	const NIDOQUEEN  ; 26
	const NIDORAN_M  ; 27
	const NIDORINO   ; 28
	const NIDOKING   ; 29
	const CLEFAIRY   ; 2a
	const CLEFABLE   ; 2b
	const VULPIX     ; 2c
	const NINETALES  ; 2d
	const JIGGLYPUFF ; 2e
	const WIGGLYTUFF ; 2f
	const ZUBAT      ; 30
	const GOLBAT     ; 31
	const ODDISH     ; 32
	const GLOOM      ; 33
	const VILEPLUME  ; 34
	const PARAS      ; 35
	const PARASECT   ; 36
	const VENONAT    ; 37
	const VENOMOTH   ; 38
	const DIGLETT    ; 39
	const DUGTRIO    ; 3a
	const MEOWTH     ; 3b
	const PERSIAN    ; 3c
	const PSYDUCK    ; 3d
	const GOLDUCK    ; 3e
	const MANKEY     ; 3f
	const PRIMEAPE   ; 40
	const GROWLITHE  ; 41
	const ARCANINE   ; 42
	const POLIWAG    ; 43
	const POLIWHIRL  ; 44
	const POLIWRATH  ; 45
	const ABRA       ; 46
	const KADABRA    ; 47
	const ALAKAZAM   ; 48
	const MACHOP     ; 49
	const MACHOKE    ; 4a
	const MACHAMP    ; 4b
	const BELLSPROUT ; 4c
	const WEEPINBELL ; 4d
	const VICTREEBEL ; 4e
	const TENTACOOL  ; 4f
	const TENTACRUEL ; 50
	const GEODUDE    ; 51
	const GRAVELER   ; 52
	const GOLEM      ; 53
	const PONYTA     ; 54
	const RAPIDASH   ; 55
	const SLOWPOKE   ; 56
	const SLOWBRO    ; 57
	const MAGNEMITE  ; 58
	const MAGNETON   ; 59
	const FARFETCH_D ; 5a
	const DODUO      ; 5b
	const DODRIO     ; 5c
	const SEEL       ; 5d
	const DEWGONG    ; 5e
	const GRIMER     ; 5f
	const MUK        ; 60
	const SHELLDER   ; 61
	const CLOYSTER   ; 62
	const GASTLY     ; 63
	const HAUNTER    ; 64
	const GENGAR     ; 65
	const ONIX       ; 66
	const DROWZEE    ; 67
	const HYPNO      ; 68
	const KRABBY     ; 69
	const KINGLER    ; 6a
	const VOLTORB    ; 6b
	const ELECTRODE  ; 6c
	const EXEGGCUTE  ; 6d
	const EXEGGUTOR  ; 6e
	const CUBONE     ; 6f
	const MAROWAK    ; 70
	const HITMONLEE  ; 71
	const HITMONCHAN ; 72
	const LICKITUNG  ; 73
	const KOFFING    ; 74
	const WEEZING    ; 75
	const RHYHORN    ; 76
	const RHYDON     ; 77
	const CHANSEY    ; 78
	const TANGELA    ; 79
	const KANGASKHAN ; 7a
	const HORSEA     ; 7b
	const SEADRA     ; 7c
	const GOLDEEN    ; 7d
	const SEAKING    ; 7e
	const STARYU     ; 7f
	const STARMIE    ; 80
	const MR__MIME   ; 81
	const SCYTHER    ; 82
	const JYNX       ; 83
	const ELECTABUZZ ; 84
	const MAGMAR     ; 85
	const PINSIR     ; 86
	const TAUROS     ; 87
	const MAGIKARP   ; 88
	const GYARADOS   ; 89
	const LAPRAS     ; 8a
	const DITTO      ; 8b
	const PORYGON    ; 8c
	const OMANYTE    ; 8d
	const OMASTAR    ; 8e
	const KABUTO     ; 8f
	const KABUTOPS   ; 90
	const AERODACTYL ; 91
	const SNORLAX    ; 92
	const ARTICUNO   ; 93
	const ZAPDOS     ; 94
	const MOLTRES    ; 95
	const DRATINI    ; 96
	const DRAGONAIR  ; 97
	const DRAGONITE  ; 98
	const MEWTWO     ; 99
	const MEW        ; 9a
	const CHIKORITA  ; 9b
	const BAYLEEF    ; 9c
	const MEGANIUM   ; 9d
	const CYNDAQUIL  ; 9e
	const QUILAVA    ; 9f
	const TYPHLOSION ; a0
	const TOTODILE   ; a1
	const CROCONAW   ; a2
	const FERALIGATR ; a3
	const SENTRET    ; a4
	const FURRET     ; a5
	const HOOTHOOT   ; a6
	const NOCTOWL    ; a7
	const LEDYBA     ; a8
	const LEDIAN     ; a9
	const SPINARAK   ; aa
	const ARIADOS    ; ab
	const CROBAT     ; ac
	const CHINCHOU   ; ad
	const LANTURN    ; ae
	const CLEFFA     ; af
	const IGGLYBUFF  ; b0
	const TOGEPI     ; b1
	const TOGETIC    ; b2
	const NATU       ; b3
	const XATU       ; b4
	const MAREEP     ; b5
	const FLAAFFY    ; b6
	const AMPHAROS   ; b7
	const BELLOSSOM  ; b8
	const MARILL     ; b9
	const AZUMARILL  ; ba
	const SUDOWOODO  ; bb
	const POLITOED   ; bc
	const HOPPIP     ; bd
	const SKIPLOOM   ; be
	const JUMPLUFF   ; bf
	const AIPOM      ; c0
	const SUNKERN    ; c1
	const SUNFLORA   ; c2
	const YANMA      ; c3
	const WOOPER     ; c4
	const QUAGSIRE   ; c5
	const MURKROW    ; c6
	const SLOWKING   ; c7
	const MISDREAVUS ; c8
	const UNOWN      ; c9
	const WOBBUFFET  ; ca
	const GIRAFARIG  ; cb
	const PINECO     ; cc
	const FORRETRESS ; cd
	const DUNSPARCE  ; ce
	const GLIGAR     ; cf
	const STEELIX    ; d0
	const SNUBBULL   ; d1
	const GRANBULL   ; d2
	const QWILFISH   ; d3
	const SCIZOR     ; d4
	const SHUCKLE    ; d5
	const HERACROSS  ; d6
	const SNEASEL    ; d7
	const TEDDIURSA  ; d8
	const URSARING   ; d9
	const SLUGMA     ; da
	const MAGCARGO   ; db
	const SWINUB     ; dc
	const PILOSWINE  ; dd
	const CORSOLA    ; de
	const REMORAID   ; df
	const OCTILLERY  ; e0
	const DELIBIRD   ; e1
	const MANTINE    ; e2
	const SKARMORY   ; e3
	const HOUNDOUR   ; e4
	const HOUNDOOM   ; e5
	const KINGDRA    ; e6
	const PHANPY     ; e7
	const DONPHAN    ; e8
	const PORYGON2   ; e9
	const STANTLER   ; ea
	const SMEARGLE   ; eb
	const TYROGUE    ; ec
	const HITMONTOP  ; ed
	const SMOOCHUM   ; ee
	const ELEKID     ; ef
	const MAGBY      ; f0
	const MILTANK    ; f1
	const BLISSEY    ; f2
	const RAIKOU     ; f3
	const ENTEI      ; f4
	const SUICUNE    ; f5
	const LARVITAR   ; f6
	const PUPITAR    ; f7
	const TYRANITAR  ; f8
	const LUGIA      ; f9
	const HO_OH      ; fa
	const CELEBI     ; fb
DEF NUM_POKEMON EQU const_value - 1
	const_skip       ; fc
	const EGG        ; fd

; Unown forms
; indexes for:
; - UnownWords (see data/pokemon/unown_words.asm)
; - UnownPicPointers (see data/pokemon/unown_pic_pointers.asm)
; - UnownAnimationPointers (see gfx/pokemon/unown_anim_pointers.asm)
; - UnownAnimationIdlePointers (see gfx/pokemon/unown_idle_pointers.asm)
; - UnownBitmasksPointers (see gfx/pokemon/unown_bitmask_pointers.asm)
; - UnownFramesPointers (see gfx/pokemon/unown_frame_pointers.asm)
	const_def 1
	const UNOWN_A ;  1
	const UNOWN_B ;  2
	const UNOWN_C ;  3
	const UNOWN_D ;  4
	const UNOWN_E ;  5
	const UNOWN_F ;  6
	const UNOWN_G ;  7
	const UNOWN_H ;  8
	const UNOWN_I ;  9
	const UNOWN_J ; 10
	const UNOWN_K ; 11
	const UNOWN_L ; 12
	const UNOWN_M ; 13
	const UNOWN_N ; 14
	const UNOWN_O ; 15
	const UNOWN_P ; 16
	const UNOWN_Q ; 17
	const UNOWN_R ; 18
	const UNOWN_S ; 19
	const UNOWN_T ; 20
	const UNOWN_U ; 21
	const UNOWN_V ; 22
	const UNOWN_W ; 23
	const UNOWN_X ; 24
	const UNOWN_Y ; 25
	const UNOWN_Z ; 26
DEF NUM_UNOWN EQU const_value - 1 ; 26
