; See song sections in audio.asm.

Music:
; entries correspond to MUSIC_* constants
	table_width 3, Music
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
; new to Crystal
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	assert_table_length NUM_MUSIC_SONGS
